#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path("lib", __dir__)

require "configuration"
require "item_extractor"
require "output_generator"
require "report_collector"

Configuration.call(ARGV)
  .then { |config| ReportCollector.call(config) }
  .then { |config, reports| ItemExtractor.call(config, reports) }
  .then { |config, items| OutputGenerator.call(config, items) }
